# Generated by Django 4.2 on 2023-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjob',
            name='task_started',
            field=models.BooleanField(default=False),
        ),
    ]
