# Generated by Django 4.2 on 2023-05-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0002_scheduledjob_task_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledjob',
            name='task_started',
        ),
    ]
